In [1]:
import numpy as np

In [2]:
A=np.random.rand?

In [4]:
A=np.random.rand(5,4)
B=np.random.rand(5,4)

In [10]:
A.T @ B

array([[ 1.40587551,  1.45974093,  0.92427431,  1.41819259],
       [ 1.42754236,  1.38811309,  1.28818827,  1.04098699],
       [ 1.04528197,  1.11691143,  1.04456565,  0.76874375],
       [ 1.55008634,  2.0848985 ,  1.20148591,  1.50578889]])

In [11]:
B.T @ A

array([[ 1.40587551,  1.42754236,  1.04528197,  1.55008634],
       [ 1.45974093,  1.38811309,  1.11691143,  2.0848985 ],
       [ 0.92427431,  1.28818827,  1.04456565,  1.20148591],
       [ 1.41819259,  1.04098699,  0.76874375,  1.50578889]])

In [12]:
x=np.random.rand(3)
y=np.random.rand(3)

In [13]:
np.dot(x,y)

0.462546452530333

In [14]:
np.dot(y,x)

0.462546452530333

In [15]:
np.dot(x.T,x)

0.7103883845971799

In [17]:
np.sqrt(np.dot(x,x.T))

0.84284540966726507

In [18]:
np.invert?

In [22]:
A=np.random.rand(3,3)

In [23]:
np.linalg.inv(A)

array([[-3.99803389,  6.24104278, -1.53847957],
       [ 4.92925187, -3.26439818, -2.30621045],
       [ 0.41452586, -1.63945683,  2.30376062]])

In [24]:
np.linalg.inv(A) @ A

array([[  1.00000000e+00,   3.18040818e-16,   3.47260328e-16],
       [  1.39658272e-16,   1.00000000e+00,   3.00919946e-17],
       [ -2.99458647e-17,   4.19642147e-18,   1.00000000e+00]])

In [25]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [26]:
np.allclose(np.linalg.inv(A) @ A,np.eye(3))

True

In [27]:
(np.linalg.inv(A) @ A) == np.eye(3)

array([[False, False, False],
       [False, False, False],
       [False, False, False]], dtype=bool)

In [29]:
import pandas as pd

In [36]:
msft=pd.read_csv('MSFT.csv',dtype={'Volume':np.float64})

In [37]:
msft[:2]

Date        Open        High         Low       Close   Adj Close  \
0  2018-12-31  101.290001  102.400002  100.440002  101.570000  101.138069   
1  2019-01-02   99.550003  101.750000   98.940002  101.120003  100.689987   

       Volume  
0  33173800.0  
1  35329300.0

In [38]:
msft[-1:]

Date    Open    High         Low       Close   Adj Close      Volume
61  2019-03-29  118.07  118.32  116.959999  117.940002  117.940002  25392200.0

In [39]:
msft.dtypes

Date          object
Open         float64
High         float64
Low          float64
Close        float64
Adj Close    float64
Volume       float64
dtype: object

In [43]:
msft2=pd.read_csv('MSFT.csv',index_col=['Date'],parse_dates=True,infer_datetime_format=True)

In [44]:
msft2.head()

Open        High         Low       Close   Adj Close  \
Date                                                                     
2018-12-31  101.290001  102.400002  100.440002  101.570000  101.138069   
2019-01-02   99.550003  101.750000   98.940002  101.120003  100.689987   
2019-01-03  100.099998  100.190002   97.199997   97.400002   96.985802   
2019-01-04   99.720001  102.510002   98.930000  101.930000  101.496536   
2019-01-07  101.639999  103.269997  100.980003  102.059998  101.625984   

              Volume  
Date                  
2018-12-31  33173800  
2019-01-02  35329300  
2019-01-03  42579100  
2019-01-04  44060600  
2019-01-07  35656100

In [60]:
hnb=pd.read_csv('https://www.hnb.hr/tecajn/htecajn.htm',
                sep='\s+',decimal=',', skiprows=[0], header=None); hnb

0         1         2         3
0   036AUD001  4.671705  4.685762  4.699819
1   124CAD001  4.910310  4.925085  4.939860
2   203CZK001  0.286674  0.287537  0.288400
3   208DKK001  0.991599  0.994583  0.997567
4   348HUF100  2.307313  2.314256  2.321199
5   392JPY100  5.950311  5.968216  5.986121
6   578NOK001  0.764522  0.766822  0.769122
7   752SEK001  0.711820  0.713962  0.716104
8   756CHF001  6.620860  6.640782  6.660704
9   826GBP001  8.654176  8.680217  8.706258
10  840USD001  6.590210  6.610040  6.629870
11  977BAM001  3.784983  3.796372  3.807761
12  978EUR001  7.402783  7.425058  7.447333
13  985PLN001  1.721097  1.726276  1.731455

In [63]:
hnb["Country"] = hnb[0].apply(lambda x: x[3:6])

In [64]:
hnb.head()

0         1         2         3 Country
0  036AUD001  4.671705  4.685762  4.699819     AUD
1  124CAD001  4.910310  4.925085  4.939860     CAD
2  203CZK001  0.286674  0.287537  0.288400     CZK
3  208DKK001  0.991599  0.994583  0.997567     DKK
4  348HUF100  2.307313  2.314256  2.321199     HUF

In [67]:
hnb["Unit"] = hnb[0].apply(lambda x: float(x[-3:]))

In [68]:
hnb.head()

0         1         2         3 Country   Unit
0  036AUD001  4.671705  4.685762  4.699819     AUD    1.0
1  124CAD001  4.910310  4.925085  4.939860     CAD    1.0
2  203CZK001  0.286674  0.287537  0.288400     CZK    1.0
3  208DKK001  0.991599  0.994583  0.997567     DKK    1.0
4  348HUF100  2.307313  2.314256  2.321199     HUF  100.0

In [69]:
hnb.drop(0, axis=1, inplace=True)
hnb.head()

1         2         3 Country   Unit
0  4.671705  4.685762  4.699819     AUD    1.0
1  4.910310  4.925085  4.939860     CAD    1.0
2  0.286674  0.287537  0.288400     CZK    1.0
3  0.991599  0.994583  0.997567     DKK    1.0
4  2.307313  2.314256  2.321199     HUF  100.0

In [70]:
pd.read_json('http://api.hnb.hr/tecajn/v1')

Broj tečajnice Datum primjene               Država  Jedinica  \
0               64     30.03.2019           Australija         1   
1               64     30.03.2019               Kanada         1   
2               64     30.03.2019                Češka         1   
3               64     30.03.2019               Danska         1   
4               64     30.03.2019             Mađarska       100   
5               64     30.03.2019                Japan       100   
6               64     30.03.2019             Norveška         1   
7               64     30.03.2019              Švedska         1   
8               64     30.03.2019            Švicarska         1   
9               64     30.03.2019     Velika Britanija         1   
10              64     30.03.2019                  SAD         1   
11              64     30.03.2019  Bosna i Hercegovina         1   
12              64     30.03.2019                  EMU         1   
13              64     30.03.2019              Poljska         1   

   Kupovni za devize Prodajni za devize Srednji za devize Valuta  Šifra valute  
0           4,671705           4,699819          4,685762    AUD            36  
1           4,910310           4,939860          4,925085    CAD           124  
2           0,286674           0,288400          0,287537    CZK           203  
3           0,991599           0,997567          0,994583    DKK           208  
4           2,307313           2,321199          2,314256    HUF           348  
5           5,950311           5,986121          5,968216    JPY           392  
6           0,764522           0,769122          0,766822    NOK           578  
7           0,711820           0,716104          0,713962    SEK           752  
8           6,620860           6,660704          6,640782    CHF           756  
9           8,654176           8,706258          8,680217    GBP           826  
10          6,590210           6,629870          6,610040    USD           840  
11          3,784983           3,807761          3,796372    BAM           977  
12          7,402783           7,447333          7,425058    EUR           978  
13          1,721097           1,731455          1,726276    PLN           985