https://github.com/jakevdp/PythonDataScienceHandbook/

https://bitbucket.org/hrojas/learn-pandas

https://github.com/ajcr/100-pandas-puzzles


In [1]:
#!ls

In [2]:
# Enable inline plotting
%matplotlib inline

In [3]:
import matplotlib.pyplot as plt
import pandas as pd 
import sys 
import matplotlib 
import numpy as np

In [4]:
print('Python version ' + sys.version)
print('Pandas version ' + pd.__version__)
print('Matplotlib version ' + matplotlib.__version__)

Python version 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
Pandas version 0.23.4
Matplotlib version 2.2.3


In [8]:
13**23

41753905413413116367045797

In [9]:
13.**23

4.175390541341312e+25

In [13]:
np.sin(np.pi)

1.2246467991473532e-16

In [14]:
 a = np.array(range(1,11)); a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
 b=a.reshape(2,5); b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [16]:
b[1,1] = 42.

In [17]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6, 42,  8,  9, 10]])

In [18]:
a

array([ 1,  2,  3,  4,  5,  6, 42,  8,  9, 10])

In [19]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

84.3 ms ± 1.65 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
933 µs ± 66.1 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [20]:
%timeit min(big_array)
%timeit np.min(big_array)

58.8 ms ± 1.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
413 µs ± 11.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [21]:
M = np.random.random((3, 4))
print(M)

[[0.43078488 0.48418744 0.1105175  0.34076791]
 [0.50773873 0.4238867  0.03645445 0.16418203]
 [0.58403124 0.58744497 0.56035738 0.47788693]]


In [22]:
M.sum()

4.708240167231924

In [23]:
M.min(axis=0)

array([0.43078488, 0.4238867 , 0.03645445, 0.16418203])

In [24]:
M.max(axis=1)

array([0.48418744, 0.50773873, 0.58744497])